Clean string. Fixes #18
eeue56/json-to-elm pull request #21
Opened 2017-02-09 01:39 UTC by tmcw

2017-02-09 11:41 UTC, eeue56 commented on elm/TypeAlias.elm
> +       parts = split All (regex "[_.\\- ]") name
A regex like this can introduce runtime errors - best ot stick at the top level, e.g

```
badCharsRegex = regex "[_.\\- ]"`

2017-02-09 11:42 UTC, eeue56 commented on elm/TypeAlias.elm
> +          (List.map capitalize (List.drop 1 parts)))
🎨  there's a lot of parens here. Try using `|>` instead, or a `[]`

2017-02-09 11:44 UTC, eeue56 requested changes
Left a couple of small comments -  fix and I'll merge :)

2017-02-11 02:33 UTC, tmcw commented
👍 Fixed the noted issues.

2017-02-11 14:33 UTC, merged